### ISSUE TITLE
"curl -L <git url> | sh" doesnt add it to the system path on OSX

### ISSUE THREAD

**Issue by kaustavha** [luvit/lit#104]
The installation instructions are mildly flawed imo. 
"curl -L <git url> | sh" simply installs lit in the pwd therefore one can't run 'lit' from the cmdline.
Symlinks from /usr/local/bin return "-bash: ./lit: Too many levels of symbolic links".
One must do a "mv <pwd>/lit /usr/local/bin".

SysInfo: MBP running OSX Yosemite v10.10.

**Comment by creationix** [comment]
I'm not sure what you mean by symlinks.  The instructions clearly state that lit is built in cwd and you need to put it in your path somewhere.

> When done, you will have a lit or lit.exe executable in your directory that you can put somewhere in your path to install globally.

Not everyone wants it installed to `/usr/local/bin` and especially by a script they are curling from the internet.  That would require sudo on most systems.  It's bad enough security practice to pipe curl to sh, but sh with sudo is worse.

**Comment by kaustavha** [comment]
Ah gotcha, missed the line you quoted.
