### ISSUE TITLE
get-lit.ps1 on Windows 32bit fails. 

### ISSUE THREAD

**Issue by rphillips** [luvit/lit#105]
This [1] needs some smarter detection: https://github.com/luvit/lit/blob/master/get-lit.ps1#L5

64bits:
```
C:> $ENV:PROCESSOR_ARCHITECTURE
IA64
```
32bits:
```
C:> $ENV:PROCESSOR_ARCHITECTURE
x86
```

**Comment by kaustavha** [comment]
Note: changing line 9 to "windows-ia32' solved this

**Comment by creationix** [comment]
So we can compare it with `IA64` and use the 64-bit version in that case?  I'm not quite sure how to do this in powershell.

**Comment by rphillips** [comment]
something like
```powershell
if ($ENV:PROCESSOR_ARCHITECTURE -eq "IA64") {
  $LUVI_ARCH = "Windows-amd64"
}
elseif ($ENV:PROCESSOR_ARCHITECTURE -eq "x86") {
  $LUVI_ARCH = "Windows-ia32"
}
```

**Comment by kaustavha** [comment]
Or
if ([System.Environment]::Is64BitProcess) {
# Do 64-bit stuff
} else {
#Do 32-bit stuff
}
