### ISSUE TITLE
An error about lit

### ISSUE THREAD

**Issue by boyzhouyi** [luvit/lit#110]
I met an error when I used lit to create single-binary executables. 

 I follow this document：https://github.com/luvit/lit/wiki/Creating-Your-First-Package

 my system release is CentOS release 6.6 (Final)

![image](https://cloud.githubusercontent.com/assets/4142077/9025757/3d1abaa0-3946-11e5-9ace-fd67a8b8bf23.png)

Can you give me some advice?

**Comment by creationix** [comment]
I'm not sure what the problem.  I'm currently working on improving the error reporting in that code.  I'll let you know when it's ready for testing.

**Comment by creationix** [comment]
Ok, do a `lit update` to get version 2.1.12 and see what error it gives now.

**Comment by creationix** [comment]
Though I'm pretty sure the problem is my code is assuming a filters list in your package.lua.  I'll see if I can make it work without one.

**Comment by creationix** [comment]
Ok, I think I fixed the problem, try again with version `2.1.13`.

**Comment by boyzhouyi** [comment]
Oh. fantastic. it's working well. 
![image](https://cloud.githubusercontent.com/assets/4142077/9089109/2b79cf34-3bc6-11e5-9e0e-f760c89730ae.png)
