### ISSUE TITLE
lit init

### ISSUE THREAD

**Issue by james2doyle** [luvit/lit#124]
It would be cool if lit had an init command like npm to scaffold out a basic `package.lua` file or write to the head of a single `init.lua` file ala [luv-mime](https://github.com/creationix/luv-mime/blob/master/init.lua) or micro libraries like that.

**Comment by creationix** [comment]
I think that could work.  Did you want to try and write it yourself?  Just add a new file at `commands/init.lua`.  I'm leaving for a two-week vacation tomorrow and won't get to this any time soon.

To develop a custom lit simply make a recursive clone of lit and run it using luvi.

```sh
git clone git@github.com:luvit/lit.git --recursive
cd lit
luvi . -- init
```

**Comment by james2doyle** [comment]
Ok cool. I can take a crack at it. Might be able to get something going by the weekend

**Comment by creationix** [comment]
Awesome, I look forward to it!
