### ISSUE TITLE
No git submodule in GitHubs release files

### ISSUE THREAD

**Issue by joerg-krause** [luvit/lit#128]
The downloadable GitHub release files (zip and tar.gz) lacks the files for the *git submodule*. Can you provide self uploaded release files, please?

**Comment by creationix** [comment]
The lit service provides these as they are required for the get-lit scripts.
https://github.com/luvit/lit/blob/master/get-lit.sh#L8

**Comment by creationix** [comment]
While it's not quite the same thing, it's just a dump of the lit package as published to lit.  But in practice, it's the same as this repo with the submodule included.

**Comment by joerg-krause** [comment]
I see! Many thanks!
