### ISSUE TITLE
Updateing -> Updating

### ISSUE THREAD

**Issue by james2doyle** [luvit/lit#130]
![spelling](http://cl.ly/image/1n1j3I1G2O2g/Image%202015-10-28%20at%201.48.46%20PM.png)

I couldn't find where this was in the lit code.

**Comment by squeek502** [comment]
Here it is: https://github.com/luvit/lit/blob/master/libs/auto-updater.lua#L75

**Comment by creationix** [comment]
Was fixed in https://github.com/luvit/lit/pull/131
