### ISSUE TITLE
Building lit on a non-supported platform

### ISSUE THREAD

**Issue by Annwenn** [luvit/lit#136]
Hi. I successfully built and installed `luvi` on my 32-bit Mac Pro, but building `lit` is somewhat more… complicated. At some point, even though I **have** luvi installed, the Makefile **or** a shell script **or** core.lua wants to download a prebuilt version from Github. 

How can I simply launch the building process using the local `luvi` installation?

```
downloading: https://github.com/luvit/luvi/releases/download/v2.3.5/luvi-regular-Darwin_i386
fail: [string "bundle:/libs/core.lua"]:227: Problem downloading custom luvi: https://github.com/luvit/luvi/releases/download/v2.3.5/luvi-regular-Darwin_i386
stack traceback:
        [C]: in function 'assert'
        [string "bundle:/libs/core.lua"]:227: in function 'getLuvi'
        [string "bundle:/libs/core.lua"]:372: in function 'makeUrl'
        [string "bundle:/libs/auto-updater.lua"]:74: in function 'check'
        [string "bundle:/commands/update.lua"]:119: in function 'fn'
        [string "bundle:deps/require.lua"]:291: in function 'require'
        [string "bundle:/main.lua"]:50: in function <[string "bundle:/main.lua"]:38>
        [C]: in function 'xpcall'
        [string "bundle:/main.lua"]:38: in function <[string "bundle:/main.lua"]:31>
```

**Comment by Annwenn** [comment]
Okay, found that I had luvi version `luvi v2.3.5-6-g730d0ca` which did not match with the wanted version

**Comment by creationix** [comment]
The `lit make` command optionally accepts a path to lit.  See https://github.com/luvit/lit/blob/master/commands/make.lua#L8

For example do:

```sh
> path/to/luvi path/to/lit -- make path/to/lit output/lit path/to/luvi
```

**Comment by Annwenn** [comment]
Okay, thank you a lot :)

**Comment by DBarney** [comment]
Dug a bit with @Annwenn on the IRC, his custom built luvi on the v2.3.5 tag is reporting its version as `/usr/local/bin/luvi v2.3.5-6-g730d0ca`

which looks like it can't match the regex at https://github.com/luvit/lit/blob/master/libs/core.lua#L201-L203 so it defaults to downloading it.

**Comment by creationix** [comment]
@Annwenn correct, the three args to make are `/path/to/app` `/path/to/output-binary` and `/path/to/custom/luvi`.  So when building lit from a lit checkout, you'd do.

```sh
git clone --recursive git@github.com:luvit/lit.git
cd lit
path/to/luvi . -- . lit path/to/luvi
```
