### ISSUE TITLE
Uploaded release including lua-git

### ISSUE THREAD

**Issue by joerg-krause** [luvit/lit#144]
Can you provide an uploaded release file since the github archives lacks lua-git. Many thanks!

**Comment by creationix** [comment]
The release zip if built by the lit server itself as you can see in the get-lit.sh script https://github.com/luvit/lit/blob/master/get-lit.sh#L8

The latest release today is https://lit.luvit.io/packages/luvit/lit/v2.2.17 with a zip file at https://lit.luvit.io/packages/luvit/lit/v2.2.17.zip

**Comment by joerg-krause** [comment]
Many thanks for pointing out!

**Comment by joerg-krause** [comment]
There is an issue with the releases from lit.luvit.io: The checksum is different for every download, e.g.:

```sh
$ wget https://lit.luvit.io/packages/luvit/lit/v2.2.17.zip && sha256sum v2.2.17.zip && rm v2.2.17.zip
4e593c37d29b528df814d90d747e4fb01fe5d807e0423d14b883077c53dae0fd  v2.2.17.zip

$ wget https://lit.luvit.io/packages/luvit/lit/v2.2.17.zip && sha256sum v2.2.17.zip && rm v2.2.17.zip
4bdccb6e3ee2cddee6830c34ff3faf66067da17d70d83de7fd20480e236556eb  v2.2.17.zip
```

Most package managers use checksum to verify reliable package download. I'd like to add lit to Buildroot and providing a checksum for the package is really encouraged. Is there a way to get a static download package from this server?
