### ISSUE TITLE
Create simple web UI for browsing packages.

### ISSUE THREAD

**Issue by creationix** [luvit/lit#15]
This can be on the same websocket server handling the query/sync protocol.

**Comment by james2doyle** [comment]
I found [this site](http://melpa.org/#/) the other day. I thought it could be a decent starting point for a "lit packages" site.

As far as how it's made, it uses [mithriljs](http://lhorie.github.io/mithril/) and basically runs off json requests. I don't know if that is something that you care about (the site architecture) but I do like the way it is laid out and how simple it is.

**Comment by creationix** [comment]
I think for an initial version I'll just dump a static filesystem via http. (the same filesystem I was planning on exporting via fuse)
