### ISSUE TITLE
Release tarball

### ISSUE THREAD

**Issue by joerg-krause** [luvit/lit#152]
I already asked for this here https://github.com/luvit/lit/issues/144. A am able to get a zip file with all the sources included, however the download method does not provide a reliable checksum as noted in the issue (after it was closed).

Having a downloadable package with a reliable checksum would be great for integrating lit into package managers, where a checksum verification is done prior building and installing the package.

**Comment by creationix** [comment]
The ETag header should be a sha1 hash of the zip.  But I see what you mean, it's changing constantly.  I must be embedding timestamps in the zipball or something.  I'll see what I can do about making that more reliable.

**Comment by creationix** [comment]
Yep, I need to add bindings to `mz_zip_set_file_times` in luvi so that lit can set the mtimes on the files when creating the zip.  Another option would be for the server to cache the generated zip forever so that it's not generated fresh on every request.

**Comment by creationix** [comment]
Actually, I just removed the code in miniz that uses the current time when adding a file from memory.  This will be fixed in the next luvi release.  I can deploy lit.luvit.io with a new custom luvi if you need the fix now. https://github.com/luvit/luvi/commit/7e398db6f4cb47e543490d01a744d7b9119ca44e

**Comment by joerg-krause** [comment]
Many thanks! It is not that urgent. Just tell me so I can test it.

**Comment by creationix** [comment]
Ok, the new luvi is released with a new lit.  I also fixed an issue with lit where the signatures on packages would sometimes be rejected for no good reason (white space issues in the formatting).

The new lit is deployed.  Try the following to see the etag stay stable between requests.

```sh
curl -I https://lit.luvit.io/packages/luvit/lit/v2.3.1.zip
```

The etag is the sha1 of the zip with double quotes wrapped around it.

**Comment by creationix** [comment]
```sh
MacBook-Pro:lit tim$ curl -I https://lit.luvit.io/packages/luvit/lit/v2.3.1.zip
HTTP/1.1 200 OK
Server: nginx/1.9.5
Date: Wed, 16 Dec 2015 23:56:56 GMT
Content-Type: application/zip
Content-Length: 93095
Connection: keep-alive
Content-Disposition: attachment; filename=lit-v2.3.1.zip
ETag: "5c5ce880e29420acc2b88d4a85bb2d3c525f90ce"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control
X-Request-Time: 22ms

MacBook-Pro:lit tim$ curl https://lit.luvit.io/packages/luvit/lit/v2.3.1.zip | shasum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93095  100 93095    0     0   279k      0 --:--:-- --:--:-- --:--:--  280k
5c5ce880e29420acc2b88d4a85bb2d3c525f90ce  -
```

**Comment by joerg-krause** [comment]
```sh
$ curl -I https://lit.luvit.io/packages/luvit/lit/v2.3.1.zip
HTTP/1.1 200 OK
Server: nginx/1.9.5
Date: Thu, 17 Dec 2015 01:04:50 GMT
Content-Type: application/zip
Content-Length: 93095
Connection: keep-alive
Content-Disposition: attachment; filename=lit-v2.3.1.zip
ETag: "5c5ce880e29420acc2b88d4a85bb2d3c525f90ce"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control
X-Request-Time: 22ms
```

```
$ curl https://lit.luvit.io/packages/luvit/lit/v2.3.1.zip | shasum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93095  100 93095    0     0  70995      0  0:00:01  0:00:01 --:--:-- 71010
5c5ce880e29420acc2b88d4a85bb2d3c525f90ce  -
```

Great! Many thanks! I'll close this.
