### ISSUE TITLE
http://lit.luvit.io/ is down.

### ISSUE THREAD

**Issue by ConstructionFYI** [luvit/lit#154]
Returns:

{"search":"https://lit.luvit.io/search/{query}","package":"https://lit.luvit.io/packages/{author}/{name}/{version}","versions":"https://lit.luvit.io/packages/{author}/{name}","names":"https://lit.luvit.io/packages/{author}","trees":"https://lit.luvit.io/trees/{hash}","blobs":"https://lit.luvit.io/blobs/{hash}","authors":"https://lit.luvit.io/packages"}

**Comment by squeek502** [comment]
I believe that's what it's meant to return. If you want to browse lit packages, try https://luvit.io/lit.html

**Comment by creationix** [comment]
Yes, the `lit.luvit.io` domain is the raw API server.
