### ISSUE TITLE
Error while running lit init on Windows.

### ISSUE THREAD

**Issue by xpol** [luvit/lit#156]
I just installed lit on Windows and run `lit init` got the follow error:
<pre>
e:\home\xpol\myproject>lit init
lit version: 3.0.0
luvi version: v2.5.2
command: init
create config: D:\Users\xpol\AppData\Roaming\litconfig
Output to package.lua (1), or a init.lua (2)?: 1
Creating: package.lua
fail: [string "bundle:commands/init.lua"]:70: attempt to concatenate field 'username' (a nil value)
stack traceback:
        [string "bundle:commands/init.lua"]:70: in function <[string "bundle:commands/init.lua"]:1>
        [string "bundle:main.lua"]:52: in function <[string "bundle:main.lua"]:39>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:39: in function <[string "bundle:main.lua"]:31>
</pre>

**Comment by xpol** [comment]
Sorry I'm tested on windows and I never use ssh key...

**Comment by creationix** [comment]
Looks like we could use some better error reporting here. But you will be unable to publish to the lit server without an ssh key tied to your github account.

As far as username, lit-init should prompt for any missing data instead of crashing. @james2doyle or @squeek502, do either of you have a moment to help with this?

**Comment by james2doyle** [comment]
Yeah I have a minute

**Comment by james2doyle** [comment]
Should this new check or guard be added to `commands/init.lua`? 

Lit init calls `core.config`, and `core.config` calls `autoconfig`, so I'm not sure where to do this check.

**Comment by creationix** [comment]
Autoconfig shouldn't require a username since it's global.  The init command should prompt for it if missing like the auth command does.

**Comment by squeek502** [comment]
This patch should work:

```diff
@@ -65,11 +65,12 @@ return function ()
     -- trim trailing comma and space
     tags = tags:sub(0, (#tags - 2))
     return tags .. " }"
   end
 
-  local projectName = prompt("Project Name", config["username"] .. "/project-name")
+  local userName = prompt("Username", config["username"])
+  local projectName = prompt("Project Name", userName .. "/project-name")
   local projectVersion = prompt("Version", "0.0.1")
   local projectDescription = prompt("Description", "A simple description of my little package.")
   local projectTags = makeTags(prompt("Tags (Comma Separated)", "lua, lit, luvit"))
   local authorName = prompt("Author Name", getConfig("user.name"))
   local authorEmail = prompt("Author Email", getConfig("user.email"))
```

Let me know if you'd like me to submit it as a PR.

**Comment by james2doyle** [comment]
@squeek502 Stolen!

**Comment by squeek502** [comment]
:smile: 

Here's an alternative fix, because username isn't actually used for anything except the project name prompt:

```diff
-  local projectName = prompt("Project Name", config["username"] .. "/project-name")
+  local projectName = prompt("Project Name", (config["username"] or "username") .. "/project-name")
```

Not sure which is better. Here's a comparison between what the prompts look like when `config["username"]` is nil.

First fix:
```
Creating: package.lua
Username: squeek502
Project Name: (squeek502/project-name) squeek502/test
```

Alt fix:
```
Creating: package.lua
Project Name: (username/project-name) squeek502/test
```

**Comment by james2doyle** [comment]
I like the first fix personally. It emulates how `npm|bower init` work

**Comment by xpol** [comment]
@creationix

Added ssh key under windows works for me.
We should add a setup instructions in https://luvit.io/install.html (or a seprated guide), some steps like.

1. Install git for windows.
2. Follow the guide here https://help.github.com/articles/generating-ssh-keys/#platform-windows to add a SSH key.
3. `lit auth <you github username>`
