### ISSUE TITLE
Lit 3.0.0 failed to install (Windows)

### ISSUE THREAD

**Issue by squeek502** [luvit/lit#159]
```
>PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"
Downloading https://github.com/luvit/luvi/releases/download/v2.5.2/luvi-regular-Windows-ia32.exe to luvi.exe
Downloading https://lit.luvit.io/packages/luvit/lit/v3.0.0.zip to lit.zip
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At line:25 char:27
+   $downloader.DownloadFile <<<< ($url, $file)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

C:/Users/tim/Desktop/luvi/src/lua/luvibundle.lua:274: ERROR: H:\Programming\Lua\luvit-irc_clean\lit.zip is not a zip file or a folder
Remove-Item : Cannot find path 'H:\Programming\Lua\luvit-irc_clean\lit.zip' because it does not exist.
At line:36 char:12
+ Remove-Item <<<<  "lit.zip"
    + CategoryInfo          : ObjectNotFound: (H:\Programming\...c_clean\lit.zip:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by squeek502** [comment]
Manually downloading `https://lit.luvit.io/packages/luvit/lit/v3.0.0.zip`, renaming to `lit.zip` and running `luvi.exe lit.zip -- make lit.zip` worked, so it has something to do with PowerShell's `DownloadFile`.

**Comment by creationix** [comment]
That's weird.  I don't think anything changed recently that would cause this.  I used the powershell script recently on a couple windows 10 boxes without issue.

**Comment by squeek502** [comment]
Reproduced on a second Windows machine. Both running Windows 7.

**Comment by squeek502** [comment]
Has something to do with the SSL cert on the lit server. Changing the download URL in `get-lit.ps1` to `"http://lit.luvit.io/packages/luvit/lit/v$LIT_VERSION.zip"` removed the error.

**Comment by creationix** [comment]
Ahh, I updated the ssl cert recently.  I guess that client doesn't support the new signing authority.

**Comment by creationix** [comment]
For reference, the old cert was from startssl, the new one is from letsencrypt.

**Comment by creationix** [comment]
I just tested on Windows 10, it has the same error.  I guess the root certs for windows needs updating or we need to find another cert authority. (or find new instructions for installing on windows)

**Comment by creationix** [comment]
Found the issue, it wasn't the cert chain, but a change I had made to the SSL config to tighten security.  It turns out made it too tight and broke certain clients like the powershell downloader.  It's good now.
