### ISSUE TITLE
Error while running `lit make lit://luvit/luvit` on Windows.

### ISSUE THREAD

**Issue by xpol** [luvit/lit#161]
F:\luvit>lit make lit://luvit/luvit
lit version: 3.0.0
luvi version: v2.5.2
command: make lit://luvit/luvit
fail: [string "bundle:libs/pkg.lua"]:30: module 'git' not found:
        no file 'bundle:libs/deps/git'
        no file 'bundle:libs/deps/git.lua'
        no file 'bundle:libs/deps/git/init.lua'
        no file 'bundle:libs/libs/git'
        no file 'bundle:libs/libs/git.lua'
        no file 'bundle:libs/libs/git/init.lua'
        no file 'bundle:deps/git'
        no file 'bundle:deps/git.lua'
        no file 'bundle:deps/git/init.lua'
        no file 'bundle:libs/git'
        no file 'bundle:libs/git.lua'
        no file 'bundle:libs/git/init.lua'
        no field package.preload['git']
        no file '.\git.lua'
        no file 'F:\luvit\lua\git.lua'
        no file 'F:\luvit\lua\git\init.lua'
        no file 'C:\Lua\lua-5.1.5\x86\LuaRocks\2.2\lua\git.lua'
        no file 'C:\Lua\lua-5.1.5\x86\LuaRocks\2.2\lua\git\init.lua'
        no file 'C:\Lua\lua-5.1.5\x86\LuaRocks\systree\share\lua\5.1\git.lua'
        no file 'C:\Lua\lua-5.1.5\x86\LuaRocks\systree\share\lua\5.1\git\init.lua'
        no file '.\git.dll'
        no file 'F:\luvit\git.dll'
        no file 'F:\luvit\loadall.dll'
        no file 'C:\Lua\lua-5.1.5\x86\LuaRocks\systree\lib\lua\5.1\git.dll'
stack traceback:
        [C]: in function 'require'
        [string "bundle:libs/pkg.lua"]:30: in main chunk
        [string "bundle:luvit-loader.lua"]:200: in function <[string "bundle:luvit-loader.lua"]:195>
        [C]: in function 'require'
        [string "bundle:libs/core.lua"]:34: in main chunk
        [string "bundle:luvit-loader.lua"]:200: in function <[string "bundle:luvit-loader.lua"]:195>
        [C]: in function 'require'
        [string "bundle:commands/make.lua"]:2: in function <[string "bundle:commands/make.lua"]:1>
        [string "bundle:main.lua"]:52: in function <[string "bundle:main.lua"]:39>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:39: in function <[string "bundle:main.lua"]:31>

**Comment by xpol** [comment]
I the problem is `https://github.com/luvit/lit/archive/3.0.0.zip` package have not include the `deps/git` module, becasue it is a submobule. Is it possible to use git [subtree](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) instead?

**Comment by squeek502** [comment]
You're right, this section of the README will not work due to `deps/git` being a submodule:

> Once you have luvi, building lit is simple:

> ```sh
> curl -L https://github.com/luvit/lit/archive/master.zip > lit.zip
> luvi lit.zip -- make lit.zip
```

One thing that could be done would be to be add a way to get the most recent version of a package from the lit api, so that something like `https://lit.luvit.io/packages/luvit/lit/v$LIT_VERSION.zip` could be used in the README instructions instead of the github zip. Something like:

* `https://lit.luvit.io/packages/luvit/lit/latest` returns the same as `https://lit.luvit.io/packages/luvit/lit/v3.0.0`
* `https://lit.luvit.io/packages/luvit/lit/latest.zip` returns the same as `https://lit.luvit.io/packages/luvit/lit/v3.0.0.zip`.

**Comment by xpol** [comment]
Yes, update the docs is good alternative.

**Comment by creationix** [comment]
Lit 3.0.3 with the new `latest` feature is released and deployed to lit.luvit.io.

**Comment by squeek502** [comment]
@creationix Would changing the README build-from-source instructions to:

```
curl -L https://lit.luvit.io/packages/luvit/lit/latest.zip > lit.zip
luvi lit.zip -- make lit.zip
```

be an acceptable fix to this issue? The difference between that and the old instructions would be that the old instructions grabbed the latest HEAD rev of the repo, while the new ones will only grab the latest release tag.

**Comment by creationix** [comment]
Yes, that's fine.  I release often enough that it won't be far behind anyway.

**Comment by creationix** [comment]
Especially as long as there is also instructions for using a recursive git clone for people who truly want latest HEAD from source.
