### ISSUE TITLE
Not a package error if any requires are defined before exports.*

### ISSUE THREAD

**Issue by kaustavha** [luvit/lit#165]
Not sure if this is intended but if I create a package, say `main.lua` which has a few require statements before the exports e.g.
```
local fs = require('fs')
exports.name = 'a/b'
```
I get a not a package error:
```
Kaustavs-MBP:luvit-read kaustavhaldar$ lit publish main.lua
lit version: 2.2.10
luvi version: v2.3.3
command: publish main.lua
load config: /Users/kaustavhaldar/.litconfig
fail: [string "bundle:/libs/core.lua"]:128: Not a package: /Users/kaustavhaldar/Dev/luvit-read/main.lua
stack traceback:
	[C]: in function 'error'
	[string "bundle:/libs/core.lua"]:128: in function 'add'
	[string "bundle:/libs/core.lua"]:239: in function 'publish'
	[string "bundle:/commands/publish.lua"]:8: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/main.lua"]:50: in function <[string "bundle:/main.lua"]:38>
	[C]: in function 'xpcall'
	[string "bundle:/main.lua"]:38: in function <[string "bundle:/main.lua"]:31>
```

The same error occurs if the exports are defined like a table instead of keys i.e
```
exports = {
  name = '..'
  version = ...
}
```
will cause the same error but
```
exports.name = '...'
exports.version = '...'
```
wont even though the two should basically eval to the same thing.

**Comment by creationix** [comment]
This is one of the weird bits of the old lit metadata format and part of the reason for moving to a new format.  Essentially it injects an `exports` table into the environment and then evals the file with nothing else in the environment (no `require`, nothing).  The code will then execute any `exports.* = *` statements and other harmless code till it reaches something the sandbox can't run (usually a `require` call) at which point it will crash.  Since we've wrapped it in pcall, we can handle this crash and can see the values that were added to the passed in `exports` table.

This is bad for several reasons.

 - It assumes a global `exports` table that doesn't exist in normal lua, breaking compat with all other ecosystems.
 - It's still unsafe, someone could put `while true do end` at the top of a package and it would hang lit.
 - It's just weird.

**Comment by creationix** [comment]
So as of lit 3.0, the new format is a comment.

```lua
--[[lit-meta
name = ...
version = ...
]]
```

Start using the new format and if you have the energy, update existing libraries and publish as a major revision since the old lit can't use them.  I've done this for luvit's libraries and have a PR for luvit core's libraries.

**Comment by kaustavha** [comment]
How does one deal with a package.lua file?
I get this error:
```
Kaustavs-MBP:luvit-read-directory-recursive kaustavhaldar$ lit publish
lit version: 3.0.3
luvi version: v2.5.2
command: publish
load config: /Users/kaustavhaldar/.litconfig
fail: [string "bundle:libs/pkg.lua"]:44: [string "/Users/kaustavhaldar/Dev/luvit-read-directory..."]:2: unexpected symbol near '='
stack traceback:
	[C]: in function 'assert'
	[string "bundle:libs/pkg.lua"]:44: in function 'evalModule'
	[string "bundle:libs/pkg.lua"]:119: in function 'query'
	[string "bundle:libs/core.lua"]:127: in function 'add'
	[string "bundle:libs/core.lua"]:240: in function 'publish'
	[string "bundle:commands/publish.lua"]:12: in function <[string "bundle:commands/publish.lua"]:1>
	[string "bundle:main.lua"]:52: in function <[string "bundle:main.lua"]:39>
	[C]: in function 'xpcall'
	[string "bundle:main.lua"]:39: in function <[string "bundle:main.lua"]:31>
```
Trying to do a `lit publish .` on this project https://github.com/kaustavha/luvit-read-directory-recursive with this package.lua
```
--[[lit-meta
name = 'kaustavha/luvit-walk',
version = "2.0.0",
license = "Apache 2",
homepage = "https://github.com/kaustavha/luvit-read-directory-recursive",
description = "Recursively dives through directories and read the contents of all the children directories.",
tags = {"luvit", "fs", "readdirrecursive" },
dependencies = { "luvit/luvit@2" },
author = { name = 'Kaustav Haldar'},
main = { 'init.lua' },
files = {
  '**.lua',
  '!tests',
}
]]
```

**Comment by squeek502** [comment]
I believe package.lua should behave exactly the same as before; comments are only needed for single file packages.

**Comment by creationix** [comment]
Sorry for not being more clear.  This change is only for single-file modules.  Multi-file modules with a package.lua still use the plain style where they simply export the table using return.

Though I could add support for the lit-meta format (with or without the wrapping comment) at which point you could do:

```lua
name = 'kaustavha/luvit-walk',
version = "2.0.0",
license = "Apache 2",
homepage = "https://github.com/kaustavha/luvit-read-directory-recursive",
description = "Recursively dives through directories and read the contents of all the children directories.",
tags = {"luvit", "fs", "readdirrecursive" },
dependencies = { "luvit/luvit@2" },
author = { name = 'Kaustav Haldar'},
main = { 'init.lua' },
files = {
  '**.lua',
  '!tests',
}
```


But currently it needs to be the module return value so wrap that in `return { ... }`

**Comment by kaustavha** [comment]
Thanks folks!
