### ISSUE TITLE
Seemingly unable to remove dependencies in subsequent versions.

### ISSUE THREAD

**Issue by bakpakin** [luvit/lit#167]
When I publish a new version of a package with removed dependencies, they are still listed as dependencies by lit when I install again. Removing the dependency from the dependency list does not seem to remove the deps.

**Comment by creationix** [comment]
Can you compare the raw metadata for the two versions?  An example url is https://lit.luvit.io/packages/creationix/coro-wrapper/v2.0.0

**Comment by creationix** [comment]
(btw, I highly recommend installing JSONView in your browser if you're going to be working with the API a lot in the browser)

**Comment by bakpakin** [comment]
Ok, I found my problem. I just forgot to remove a dependency that included the old dependecies. Silly me.
