### ISSUE TITLE
error while make lit.

### ISSUE THREAD

**Issue by xpol** [luvit/lit#176]
after build luvi, I run

> ./luvi/build/luvi lit -- make lit

Got follow error:

fail: [string "bundle:libs/core.lua"]:382: EISDIR: illegal operation on a directory: /Users/user/Workspace/.lit.temp
stack traceback:
	[C]: in function 'assert'
	[string "bundle:libs/core.lua"]:382: in function 'make'
	[string "bundle:commands/make.lua"]:11: in function <[string "bundle:commands/make.lua"]:1>
	[string "bundle:main.lua"]:52: in function <[string "bundle:main.lua"]:39>
	[C]: in function 'xpcall'
	[string "bundle:main.lua"]:39: in function <[string "bundle:main.lua"]:31>

**Comment by creationix** [comment]
The problem is it's trying to create a binary `lit` where you already have a folder `lit`.  Either rename your folder or specify a custom target path or change to a new cwd.  I typically build it from inside the lit folder with:

```sh
../luvi/build/luvi . -- make .
```

**Comment by xpol** [comment]
Thank you very much.
I have make a pr in luvit.io https://github.com/luvit/luvit.io/pull/14.
