### ISSUE TITLE
coro-wrapper error

### ISSUE THREAD

**Issue by ccinv** [luvit/lit#203]
I ran the example server and get such error
> D:/proj/luvit.io/deps/coro-wrapper.lua:109: index must be a number if set
stack traceback:
        [C]: in function 'assert'
        D:/proj/luvit.io/deps/coro-wrapper.lua:109: in function '(for generator)'
        D:/proj/luvit.io/deps/weblit-app.lua:121: in function <D:/proj/luvit.io/deps/weblit-app.lua:119>
        [C]: in function 'xpcall'
        D:/proj/luvit.io/deps/coro-net.lua:141: in function <D:/proj/luvit.io/deps/coro-net.lua:140>

Then I edited coro-wrapper.lua and deleted `assert(type(newIndex) == "number", "index must be a number if set")`, it works.Here newIndex is a string not number.

**Comment by squeek502** [comment]
Could be related to/the same as https://github.com/luvit/lit/issues/200#issuecomment-277139210 if you're running it using `luvit`.

**Comment by SinisterRectus** [comment]
Not surprisingly, simply removing the assertion does not fix coro-http for me. It just allows for mismatched types to be used incorrectly:

`coro-wrapper.lua:82: attempt to compare number with string`

**Comment by creationix** [comment]
For now you can't use the coro-* 3.x modules with luvit since it's internal http-codec overrides the 3.x one your app uses.

Luvi apps work great though if that's an option.
