### ISSUE TITLE
Cannot fetch get-lit.ps1

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/lit#234]
Been receiving a lot of reports about this, and I've now been able to reproduce it myself.

```
Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ iex ((new-object net.webclient).DownloadString('https://github.com/lu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

**Comment by SinisterRectus** [comment]
I've created a get-lit app at https://github.com/SinisterRectus/get-lit. I may expand it further to allow for other OSes and dynamic version handling.

**Comment by squeek502** [comment]
Looks like this is the issue: https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

> By default powershell uses TLS 1.0 the site security requires TLS 1.2

This works for me:
```
PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol =  'Tls12'; iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"
```

**Comment by SinisterRectus** [comment]
Well that's interesting. I'll PR the change to luvit.io.
