### ISSUE TITLE
lit.luvit.io expired cert

### ISSUE THREAD

**Issue by ernestrc** [luvit/lit#240]
The certificate on lit.luvit.io expired on Friday, August 10, 2018 at 10:47:10 PM

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading https://lit.luvit.io/packages/luvit/lit/v3.5.4.zip
    Aborting...

**Comment by creationix** [comment]
Fixed a few days ago.  Sorry for the trouble.
