### ISSUE TITLE
Installing luvit fails! [Windows]

### ISSUE THREAD

**Issue by CleverSource** [luvit/lit#248]
I did strip most of the outputs, only the input and the error are shown.

C:\luvit>PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'; iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"

fail: [string "bundle:libs/codec.lua"]:123: No such hash: 6e805fb6a48f25304cc6553f18a01ecc30f10e30
stack traceback:
        [C]: in function 'assert'
        [string "bundle:libs/codec.lua"]:123: in function 'read'
        [string "bundle:libs/codec.lua"]:128: in function 'readAs'
        [string "bundle:libs/rdb.lua"]:165: in function 'fetch'
        [string "bundle:libs/rdb.lua"]:140: in function 'load'
        [string "bundle:deps/git/db.lua"]:395: in function 'loadAny'
        [string "bundle:libs/pkg.lua"]:132: in function 'queryDb'
        [string "bundle:libs/core.lua"]:378: in function 'makeUrl'
        [string "bundle:commands/make.lua"]:13: in function <[string "bundle:commands/make.lua"]:1>
        [string "bundle:main.lua"]:69: in function <[string "bundle:main.lua"]:56>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:56: in function <[string "bundle:main.lua"]:48>

**Comment by ronnie123442** [comment]
can reproduce windows 10 x64

**Comment by squeek502** [comment]
Not specific to Windows. Caused by https://github.com/luvit/lit/issues/247

**Comment by squeek502** [comment]
Should be fixed on the server-side now (#250).
