### ISSUE TITLE
lit publish `tag.type must be string`

### ISSUE THREAD

**Issue by Corotyest** [luvit/lit#308]
I having this error when trying to publish a single file.

![image](https://user-images.githubusercontent.com/74837790/152619282-df3ee888-4f2f-407a-9b5d-80941afbbc8c.png)

**Comment by Bilal2453** [comment]
As the error explains, you are missing the `tags` field, which is required. An example of a working metadata is:
```lua
--[[lit-meta
  name = "luvit/codec"
  version = "2.0.1"
  dependencies = {
    "luvit/utils@2.1.0",
  }
  license = "Apache 2"
  homepage = "https://github.com/luvit/luvit/blob/master/deps/codec.lua"
  description = "Utilities for working with luvit streams and codecs."
  tags = {"luvit", "codec", "stream"}
]]
```
The Lit wiki may be a bit outdated regarding this.

**Comment by Corotyest** [comment]
![image](https://user-images.githubusercontent.com/74837790/154193938-aba48ac6-a1d4-4cc1-914b-3794d9094352.png)

**Comment by Corotyest** [comment]
but if i change it to init
![image](https://user-images.githubusercontent.com/74837790/154194177-77792e49-9b90-4183-8a31-426fa5b4c1d3.png)

into task::
![image](https://user-images.githubusercontent.com/74837790/154194202-d814be5f-8c10-4062-9160-59782ae8622b.png)

**Comment by Bilal2453** [comment]
The metadata comment is only supposed to be put in a single-file module. For directory module use package.lua (just like you have done in your last example). In all of the mentioned examples, you were trying to publish a directory, which had a single module file which is not how it is done.

For a single module-file, you have something like this:
> task.lua
```lua
--[[lit-meta
  name = "Corotyest/task"
  version = "0.0.1"
  dependencies = {}
  license = "Apache 2"
  homepage = "https://github.com/Corotyest/task"
  description = "A manager for uv.new_timer..."
  tags = {"luvit", "uv", "time"}
]]
-- etc
```
And to publish it you do `lit publish task.lua` (Note the .lua indicating it is a file).

**Comment by Corotyest** [comment]
AYAYA GRACIAS TE QUIERO: THANK YOU <3 (sorry about i am dumb)
