### ISSUE TITLE
`fail: [string "bundle:libs/core.lua"]:116: system lib` Error

### ISSUE THREAD

**Issue by shawnjb** [luvit/lit#323]
While trying to authenticate with `lit`, I was greeted with a new error I haven't seen.

```
C:\Users\Shawn\GitHub\luvenv>lit auth  
lit version: 3.8.5
luvi version: v2.14.0
command: auth
load config: C:\Users\Shawn\AppData\Roaming\litconfig
username: shawnjb
name: shawnjb
email: 129807902+shawnjb@users.noreply.github.com
privateKey: C:\Users\Shawn\.ssh\id_rsa
fail: [string "bundle:libs/core.lua"]:116: system lib
stack traceback:
        [C]: in function 'assert'
        [string "bundle:libs/core.lua"]:116: in function 'getKey'
        [string "bundle:libs/core.lua"]:357: in function 'authUser'
        [string "bundle:commands/auth.lua"]:63: in function <[string "bundle:commands/auth.lua"]:1>
        [string "bundle:main.lua"]:69: in function <[string "bundle:main.lua"]:56>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:56: in function <[string "bundle:main.lua"]:48>
```

**Comment by shawnjb** [comment]
I'd like to also mention that the private key at `C:\Users\Shawn\.ssh\id_rsa` was automatically assigned and the file has the correct private key.

**Comment by Bilal2453** [comment]
That is an OpenSSL error.  It is happening on pkey.read.  I can't really find much online about it.

**Comment by shawnjb** [comment]
> That is an OpenSSL error. It is happening on pkey.read. I can't really find much about it online.

Re-installing OpenSSH to see if that resolves the issue.

**Comment by Bilal2453** [comment]
I have high doubts that would help with anything.  Could you regenerate the key according to the method describe in [the wiki](https://github.com/luvit/lit/wiki/Creating-Your-First-Package)?
`ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -m PEM`

**Comment by shawnjb** [comment]
> I have high doubts that would help with anything. Could you regenerate the key according to the method describe in [the wiki](https://github.com/luvit/lit/wiki/Creating-Your-First-Package)? `ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -m PEM`

This method worked, my mistake was using 1Password's SSH agent to generate an RSA key. Thank you.
