### ISSUE TITLE
Implement windows version of web-install.sh

### ISSUE THREAD

**Issue by creationix** [luvit/lit#33]
This can use powershell

**Comment by rphillips** [comment]
I took a stab this morning on creating a powershell version: https://github.com/luvit/lit/blob/master/web-install.ps1

Just need to tag a release:

```@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/luvit/lit/a1bef9c234cf2569ded3b5c7516277c0f5746f70/web-install.ps1'))"```

**Comment by creationix** [comment]
Like this? `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/0.9.4/web-install.ps1'))"`

**Comment by creationix** [comment]
Seems to work great!  Tested in a powershell by just pasting in the command string.
