### ISSUE TITLE
ENOENT on saving github keys on windows

### ISSUE THREAD

**Issue by IZEDx** [luvit/lit#52]
When doing lit auth on windows it downloads the ssh keys of the corresponding github account as it should, but can't save it, since windows does not allow filenames to contain ":", thus resulting in lit auth failing.

Error stack:
>
	fail: [string "bundle:/libs/storage.lua"]:86: ENOENT: no such file or directory:
	%APPDATA%\litdb.git\keys\IZEDx\0d:a7:0a:13:de:d1:b0:12:92
	:28:6b:14:b5:33:0a:d9
	stack traceback:
	        [C]: in function 'assert'
	        [string "bundle:/libs/storage.lua"]:86: in function 'putKey'
	        [string "bundle:/libs/core.lua"]:193: in function 'importKeys'
	        [string "bundle:/libs/core.lua"]:212: in function 'authUser'
	        [string "bundle:/commands/auth.lua"]:46: in function 'fn'
	        [string "bundle:deps/require.lua"]:174: in function 'require'
	        [string "bundle:main.lua"]:14: in function <[string "bundle:main.lua"]:9
	        [C]: in function 'xpcall'
	        [string "bundle:main.lua"]:9: in function <[string "bundle:main.lua"]:7>

**Comment by creationix** [comment]
Thanks.  I guess in all my testing, I never actually ran lit auth on windows.  I have even published windows binaries to lit as you can see at http://lit.luvit.io/trees/76574d01942112a9ca756375b2deeaaa5deda641/creationix/glfw-v3.1.2/Windows-x64.

**Comment by creationix** [comment]
Fixed in https://github.com/luvit/lit/commit/2b4d9fb112bb8d9612dcedfe27fe5e6a83fc9e44.  I tested with `lit auth` on my windows box and it worked. (I have git for windows installed and had previously created an rsa key in the bundled git bash)
