### ISSUE TITLE
Missing dll dependency for the Windows installer

### ISSUE THREAD

**Issue by rivenz** [luvit/lit#54]
Hello everyone,

I tested the powershell installer on a freshly installed computer running Windows 8.1
 
The installation failed, because the the luvi.exe requires the msvcr120.dll that is provided by Microsoft Visual Studio 2013 Runtime package. Putting the missing dll on the same folder path solved the installation issue.

**Comment by rjemanuele** [comment]
this is fixed in the latest lit that contains the new luvi
