### ISSUE TITLE
lit selfupdate

### ISSUE THREAD

**Issue by james2doyle** [luvit/lit#55]
It would be nice if `lit` could update itself, or even just notify that there is an update available.

Even having something like a [update-notifier](https://www.npmjs.com/package/update-notifier) approach, that's just a simple message, would be nice. Bower, the package manager, gives you a notice when you run `bower install` with an outdated version.

Does this resonate with anyone else?

**Comment by creationix** [comment]
Yes, this is a great idea.

**Comment by james2doyle** [comment]
Sweet. Just having an [update-notifier](https://www.npmjs.com/package/update-notifier) port to lit/luvit would be awesome.

**Comment by creationix** [comment]
WIP at #57

**Comment by creationix** [comment]
PR ready for review

**Comment by creationix** [comment]
Merged and published as lit v1.0.3.

Also new with this is the ability to specify the luvi flavor and version in package.lua when making luvi apps.  Lit will download the right version if the currently running version doesn't match.

**Comment by creationix** [comment]
Update to latest lit using the get-lit script and then you can `lit update` to get new versions after that.

**Comment by james2doyle** [comment]
awesome!
