### ISSUE TITLE
Is there a website like https://www.npmjs.com/   to view package?

### ISSUE THREAD

**Issue by jackiesun8** [luvit/lit#58]
As it said in title.

**Comment by rphillips** [comment]
There is lit.luvit.io. For now we are using the [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en) plugin for chrome to navigate the site. A website is planned.

**Comment by creationix** [comment]
Correct, since I have limited time, I decided to only export some raw JSON data via REST and hope that someone else has time to make a nice looking interface on top of that.  I did make sure to make it hyperlinkable at least if you have JSONView installed (firefox or chrome)

**Comment by jackiesun8** [comment]
Ok,I got it. I am a game server programmer. I am planning to write a distributed game server framework for luvit.Such as like [pomelo](http://pomelo.netease.com/).As luvit is a new stuff, the package is less than nodejs,so maybe i must write some packages myself,if no one has to write it.

**Comment by creationix** [comment]
That's probably true, as you can see browsing the json, there aren't many packages yet.
