### ISSUE TITLE
Which dependency manager is official?

### ISSUE THREAD

**Issue by jackiesun8** [luvit/lit#59]
Is lit a dependency manager?And I found that in luvit's wiki there are many others manager,such as npm,lum,lui,pkg.Which one is the recommended?

**Comment by karlbohlmark** [comment]
Read the first lines of the readme : ). I'd say `lit` is the recommended package manager. It is however very new. Read the announcement for luvit 2.0: https://luvit.io/blog/luvit-reborn.html

**Comment by rphillips** [comment]
Lit is the recommended package manager for Luvit 2.

**Comment by jackiesun8** [comment]
@rphillips ok,thanks.
