### ISSUE TITLE
Allow pre/post-install scripts

### ISSUE THREAD

**Issue by lhelsloot** [luvit/lit#60]
npm allows a `scripts` property in the package metadata, containing commands to be executed at various points in a package's lifecycle, e.g. before publishing or after installation (see [npm-scripts](https://docs.npmjs.com/misc/scripts)). Such scripts are commonly used to compile native code. Should this be added as a feature to lit?

**Comment by creationix** [comment]
I'd rather not have this.  Its caused lots of trouble to npm and Isaac is constantly trying to discourage people from using it.  Is there a concrete use case where this is needed?

**Comment by james2doyle** [comment]
How about a post-install message? Sublime Text sort of does this with package control after you install or update a plugin. This way you can have something like:

*you must have `X` in your path to use this module*

or even

*please see http://example.com/usage for compile instructions before using this module*

I think Sublime Plugins do a good job of this post-install message stuff, but they serve a full text file and not just a single line

**Comment by lhelsloot** [comment]
I'm working on a package that relies on existing luarocks packages. Instead of having to include precompiled versions of those packages for multiple platforms, I wanted to use luarocks to install them when installing the lit package.

**Comment by nihildeb** [comment]
+1 for no scripts. I think @lhelsloot makes a perfect example of the type of abuse such a feature could permit. lit is a lua package manager whos job is to manage luvi app dependencies dependencies, not luarocks. If I installed a luvi package, and it went on to install a bunch of luarocks, I would be irritated to say the least. 

Also, as a dev, I expect to be able to make a standalone executable which contains all my deps after 'make' is done. Adding scripts to the lit installation means you have an inconsistent environment between where you installed the app, and where you deploy/distribute it.

**Comment by creationix** [comment]
I really don't want to enable script hooks, they are dangerous and very non-portable.  If you do have a need to mix package systems, use something higher level like chef that is made for this kind of work instead of adding responsibility to lit.
