### ISSUE TITLE
Path residue?

### ISSUE THREAD

**Issue by develephant** [luvit/lit#63]
I know what the error is telling me, but I thought I'd point out that the first path is using /home/tim/..

`/home/tim/luvi/src/lua/init.lua:390: ENOENT: no such file or directory: ...`

Best.

**Comment by creationix** [comment]
This is because init.lua is baked into luvi with debug symbols, so it stores the full path to init.lua.  I wonder if we can override the path string to improve debugging.  Something like `luvi:init.lua` would be more accurate.

**Comment by creationix** [comment]
Moved to luvi.
