### ISSUE TITLE
locating sources, docs and maintainer info

### ISSUE THREAD

**Issue by nihildeb** [luvit/lit#71]
hey, love what you guys are doing here. for me, it's the best way to work with lua I have found so far. Thanks and I hope I can help in the future.

Question though. I understand the project is young, and I look forward to seeing the search command working. What I think is a problem though, and maybe I just don't "get it" yet, but when I see something like:

>creationix/coro-wrapper

I really expected that to lead me to a git repo, where I can see the source, and perhaps some usage docs in a README or something. since there is no search, all I can do is lit install and then "magic happens" and then I can go look for some docs in deps/ but that's really a lot to do just to see if the package is even usable or applies to my use case. So either search needs to be real informative, or we need an info command, or ideally for me, there would be a git repo called creationix/coro-wrapper where I could search and create issues or whatever. I don't know where coro-wrapper exists, and i don't know why it wouldn't exist there.

I just wanted to give you my first impressions/confusions, I love the concept and the functionality so far, and I look forward to using l/it/uv/uvi/uvit. It's really the right blend of all the right techs, with just the right amount of flexibility and features to be useful in many use cases I think. Thanks again.

**Comment by james2doyle** [comment]
I've been using [james2doyle/slugify](http://lit.luvit.io/packages/james2doyle/slugify) for lit, but then [james2doyle/lit-slugify](https://github.com/james2doyle/lit-slugify) for github. I set that in the homepage property in my [package.lua](https://github.com/james2doyle/lit-slugify/blob/master/package.lua).

But you're right, there is no way to see any information (if you can't find it on github first) until you have already installed the dependency.

**Comment by nihildeb** [comment]
Thanks, there at least you have the homepage property, which I haven't seen used up until now. I guess the bigger concern I have is how to find the canonical version, to get/contribute upstream patches. coro-fs is gold to me, and I guess it just lives in the lit repo, but does it?

**Comment by nihildeb** [comment]
Maybe, my confusion is just that there is no way to distinguish something which I have written as a module to be used in my project, and a package which I have installed as a dependency from some public source. Is there a way to tell? Sorry, I feel like this might just be noise and I need to use the tool some more...

**Comment by creationix** [comment]
I'm working on this.  You can see a preview of the new search page at https://luvit.io/lit.html.  It's a simple client-side JS app that consumes the API at https://lit.luvit.io/search/james.  If you have jsonview installed in your browser, the raw API is quite usable.  Homepage is an official supported property.  YOu can see the full list at https://github.com/luvit/lit/blob/master/libs/pkg.lua#L33-L44

Feedback is appreciated, I'm trying to make this useful as I find time.

**Comment by creationix** [comment]
@nihildeb also, regarding dependencies and libraries, the require system in luvit 2.0 supports `deps` and `libs`, but lit will only install to `deps`.  The convention is to `.gitignore` the `deps` folder and install your internal libraries into `libs`.

**Comment by james2doyle** [comment]
@creationix awesome. looks good!

**Comment by creationix** [comment]
Hmm, that sample query wasn't very helpful, here are some more interesting queries:

 - https://lit.luvit.io/search/coro - Find the coro style libraries
 - https://lit.luvit.io/search/msgpack - Find my new msgpack codec (will full metadata)
 - https://lit.luvit.io/search/luvit - Mixed results including author, and packages from multiple authors with old and new packages.

**Comment by creationix** [comment]
I'm still trying to figure out a way to include documentation and/or some sample code in the search result and/or package page.  Maybe the package.lua could include a small markdown section with docs and examples?  We already have the "description" field which I plan to render as markdown, that might be enough, but then do we need a new field for a short one-line description of the page for search results?

**Comment by james2doyle** [comment]
Does anyone know how npmjs.org does it?

Each `package.json` on there has a `git` property with the type and url. It looks like they just fetch the `readme.md` from the Github and store it as page of the page (it is not fetched XHR, it comes with the GET request for the page). I took at look at the network panel when loading a page, and they just do a XHR to get the issues count and open PR count. So there is clearly a strong coupling between the npmjs.org page and the package's github page.

**Comment by creationix** [comment]
Right, npm packages are much fatter than lit packages.  I tend to only include files needed to run the library while npm includes *everything* by default and so the README.md is often inside the tarball in the npm database.

We could have people start including README.md in their package, it would also bring some level of offline documentation for people who have packages installed locally in deps.  I just hate bringing in assets that aren't needed by the runtime, especially when they get bundled in the luvi app bundles.

**Comment by creationix** [comment]
See also luvit/lit#56 and luvit/lit#72

**Comment by james2doyle** [comment]
This could be a hack suggestion, but what about having a `documentation` property pass a "valid URL test"? If it fails, it gets treated as text, if it passes it gets treated as a URL to the docs?

As an aside I think `description` *should be reserved for the package description and not any kind of documentation*. There should be a `documentation` property/key in the table to link/describe the package.

**Comment by nihildeb** [comment]
thanks for the feedback. as it is I am spending quite a bit of time in deps, just reading code to see how things work. I think it would be quite handy if there was a README.md right there with the package. I can totally get behind keeping the packages small, but documentation is awesome. Just an idea, but couldn't the README.md in the root just be filtered out during the zip. It should be pretty safe to assume that one file is not part of the apps runtime.

**Comment by nihildeb** [comment]
@james2doyle if we can't get some docs right there in the package, i would assume it would be at the homepage url. There is nothing bad about sticking in an explicit link to documentation, but it still means I have to jump out of vim and into a browser.

**Comment by james2doyle** [comment]
> if we can't get some docs right there in the package, i would assume it would be at the homepage url

Good point, but you were concerned about packages *that don't have a homepage*, so that isn't really the answer. If the docs were an explicit link, you actually wouldn't have to leave your vim because you can use `luvit -e` like so:

```shell
wget $( luvit -e "print(require('./lit-diceware/package.lua').homepage)" ) -O lit-diceware.html
```

This downloads the github page, but if there was an explicit link to docs, it could download that

**Comment by nihildeb** [comment]
bash jit one liner! nice :)

but then it would be html and I'd still need a browser (or can you fit
strip-tags into that oneliner too :)

**Comment by james2doyle** [comment]
If it were me I would use markdown for my docs. So it would be a link to an
Md file.

**Comment by creationix** [comment]
The lit database won't be hosting docs for now.  Please include a homepage link in your metadata that has documentation.
