### ISSUE TITLE
Implement package search UI at luvit.io.

### ISSUE THREAD

**Issue by creationix** [luvit/lit#72]
A start has been prototyped and deployed, more data needs to be surfaced to make the search useful.

Also the API needs consistent data between search results and package indexing directly.

**Comment by creationix** [comment]
See prototype at https://luvit.io/lit.html

**Comment by james2doyle** [comment]
Looks good.

**Comment by nihildeb** [comment]
nice! I know it's a prototype, but just sayin:
- if there are no results, say so. right now the querying... just disappears to a blank page
- links to homepages (maybe they are there, but I didn't see any)
- I can see that dep list getting out of hand (too long). it already sort of dominates the output. maybe a twisty to roll it up/down. It's not bad as it is though, just a thought...

**Comment by nihildeb** [comment]
great! thanks @squeek502 

this is really helpful Tim, thanks!

**Comment by nihildeb** [comment]
just noticed that the pluralize is not correct on the result count. When you get a single result it says:

> 1 matche

with multiple resuts it is correct, just adding the 's'

**Comment by creationix** [comment]
The lit-browser.js interface still has several issues, but now thanks to the revamped search backend, we can do more interesting things.

- [ ] Show parsed search terms as little rectangles with close buttons.  When one is closed, start up search.
- [ ] Fix results count pluralization.
- [ ] Show message when there are no results suggesting broadening the search.
- [ ] Hyperlink results when possible, for example clicking on a dependency will do a name search for that name, clicking on a tag will search for all packages with that tag, author will search for all packages by that author, etc..

**Comment by creationix** [comment]
All done and deployed to https://luvit.io/lit.html
