### ISSUE TITLE
lit make lit://luvit/luvit -g

### ISSUE THREAD

**Issue by james2doyle** [luvit/lit#77]
Essentially just a `-g/--global` flag shortcut for doing things like `lit make lit://luvit/luvit && mv luvit /usr/local/bin`

Maybe I am doing it wrong but I don't see a way to do it at the moment.

**Comment by creationix** [comment]
Correct, there is no feature for this.  I don't want to hard-code `/usr/local/bin`, but using the dirname of `uv.exepath()` is probably safe.

**Comment by james2doyle** [comment]
Ok cool. Maybe even seeing where it is installed and then just replacing it with the new one.

**Comment by creationix** [comment]
The new `lit update` command will replace luvit, lit, and luvi in-place relative to wherever lit is installed to.

**Comment by james2doyle** [comment]
Nice!
