### ISSUE TITLE
lit update confusing output

### ISSUE THREAD

**Issue by lduboeuf** [luvit/lit#80]
$:lit update
lit version: 1.2.13
luvi version: v2.0.9
command: update
load config: /home/lionel/.litconfig
**lit update available: 1.2.9**
**lit is up to date: 1.2.13**
luvit is up to date: 2.1.12
luvi is up to date: v2.0.9
done: success

**Comment by creationix** [comment]
Which part is confusing?

**Comment by lduboeuf** [comment]
lit update available: 1.2.9
lit is up to date: 1.2.13
say that a lit 1.2.9 update is available whereas lit is up to date (1.2.13)

**Comment by creationix** [comment]
Interesting.  I wonder how you reproduced that.  Is this a fresh install of lit?

**Comment by lduboeuf** [comment]
no, i did updates several times until I’ve first downloaded it.

**Comment by lduboeuf** [comment]
but at first, i did a lit built from sources.

**Comment by creationix** [comment]
Ahh, it caches the `toupdate` value so that it doesn't need to check every time the program is run.  I should probably reset that after an update so prevent a confusing situation like this
