### ISSUE TITLE
fail on windows

### ISSUE THREAD

**Issue by zhaozg** [luvit/lit#82]
compiling: libs/pkg.lua
compiling: libs/rdb.lua
compiling: libs/rules.lua
compiling: libs/vfs.lua
compiling: main.lua
compiling: package.lua
fail: [string "bundle:/libs/core.lua"]:375: attempt to call field 'processDeps'
(a nil value)
stack traceback:
        [string "bundle:/libs/core.lua"]:375: in function 'make'
        [string "bundle:/commands/make.lua"]:10: in function 'fn'
        [string "bundle:deps/require.lua"]:275: in function 'require'
        [string "bundle:/main.lua"]:32: in function <[string "bundle:/main.lua"]
:20>
        [C]: in function 'xpcall'
        [string "bundle:/main.lua"]:20: in function <[string "bundle:/main.lua"]
:13>

**Comment by creationix** [comment]
Master is currently broken.  Sorry for the trouble.

**Comment by creationix** [comment]
Master had the dangerous changes reverted and the new re-factored code is in review at https://github.com/luvit/lit/pull/84 if you could please give it a test.

**Comment by zhaozg** [comment]
OK

**Comment by zhaozg** [comment]
![image](https://cloud.githubusercontent.com/assets/542599/8097987/578ec398-101c-11e5-8df0-9d2f8c7b3ee5.png)

Test Pass
