### ISSUE TITLE
`lit publish`:  changing email

### ISSUE THREAD

**Issue by lduboeuf** [luvit/lit#83]
lit version: 1.3.0
luvi version: v2.1.0

tried to change my old email with the correct one, but don't know where to find. 
changed it in `.litconfig` and in `git config user.email`, changed  SSH keys, did `lit auth` but does not do anything while lit publishing.
http://lit.luvit.io/packages/lduboeuf/cjson/v1.0.1

**Comment by creationix** [comment]
It pulls from the lit config which is initialized using global git config I think.  Changing the litconfig should do the trick.

Can you confirm you changed the litconfig file that is printed when lit runs.

**Comment by lduboeuf** [comment]
yes, did a `lit config` and email is correct.
also `git config --global user.email` is correct

**Comment by creationix** [comment]
Lit signs the packages when you run lit add, not when you publish them.  Maybe `rm -rf ~/.litdb` and try again?

**Comment by lduboeuf** [comment]
A little tricky but that's fine now. thanks. should i close the issue or let it open for reminding ?

**Comment by creationix** [comment]
Close is fine unless there is some action or change you desire.

**Comment by lduboeuf** [comment]
the question is more for you if someone face the same trouble, this will lead to unwanted lit spamming and will take your time again ^ ^
