### ISSUE TITLE
Improve docs for making luvi apps.

### ISSUE THREAD

**Issue by silverkorn** [luvit/lit#85]
Following the installation and creating a generic application as the one on the main page of https://luvit.io/, The built application does not work since it doesn't seems to compile or search for the `deps` virtual directory (That's just a guess).

Content of __myapp__ directory:

__package.lua__
``` lua
return {
  name = "myapp",
  version = "0.0.1",
  private = true,
  dependencies = {
    "creationix/weblit@0.3.1",
  }
}
```
__main.lua__
``` lua
local weblit = require('weblit')

weblit.app
  .bind({host = "127.0.0.1", port = 1337})

  -- Configure weblit server
  .use(weblit.logger)
  .use(weblit.autoHeaders)

  -- A custom route that sends back method and part of url.
  .route({ path = "/:name"}, function (req, res)
    res.body = req.method .. " - " .. req.params.name .. "\n"
    res.code = 200
    res.headers["Content-Type"] = "text/plain"
  end)

  -- Start the server
  .start()
```

Building results:
```
PS C:\luvit> .\lit.exe make myapp
lit version: 1.2.15
luvi version: v2.0.9
command: make myapp
load config: C:\Users\Silverkorn\AppData\Roaming\litconfig
lit update available: 1.3.0
creating binary: myapp.exe
copying binary prefix: 2583040 bytes from C:\luvit\lit.exe
importing: C:\luvit\myapp
compiling: main.lua
compiling: package.lua
connecting: wss://lit.luvit.io/
adding: creationix/websocket-codec@1.0.3
compiling: deps/websocket-codec.lua
adding: creationix/weblit-static@0.3.1-1
compiling: deps/weblit-static.lua
adding: creationix/coro-channel@1.1.0
compiling: deps/coro-channel.lua
adding: creationix/coro-tcp@1.0.5-2
compiling: deps/coro-tcp.lua
adding: creationix/weblit-logger@0.1.1-1
compiling: deps/weblit-logger.lua
adding: creationix/hybrid-fs@0.1.1
compiling: deps/hybrid-fs.lua
adding: creationix/coro-fs@1.2.4
compiling: deps/coro-fs.lua
adding: creationix/mime@0.1.2-1
compiling: deps/mime.lua
adding: creationix/weblit-websocket@0.2.3-2
compiling: deps/weblit-websocket.lua
adding: creationix/weblit-auto-headers@0.1.2-1
compiling: deps/weblit-auto-headers.lua
adding: creationix/weblit-app@0.2.6-1
compiling: deps/weblit-app.lua
adding: creationix/coro-tls@1.2.0
compiling: deps/coro-tls.lua
adding: creationix/hex-bin@1.0.0-1
compiling: deps/hex-bin.lua
adding: creationix/weblit@0.3.2
including: package.lua
including: init.lua
compiling: deps/weblit/init.lua
compiling: deps/weblit/package.lua
adding: creationix/coro-wrapper@1.0.0-1
compiling: deps/coro-wrapper.lua
adding: luvit/http-codec@1.0.0-1
compiling: deps/http-codec.lua
adding: creationix/weblit-etag-cache@0.1.1-1
compiling: deps/weblit-etag-cache.lua
adding: luvit/querystring@1.0.0-1
compiling: deps/querystring.lua
done building: myapp.exe
done: success
```

Running results:
```
PS C:\luvit> .\myapp.exe
[string "bundle:main.lua"]:1: module 'weblit' not found:
        no field package.preload['weblit']
        no file '.\weblit.lua'
        no file 'C:\luvit\lua\weblit.lua'
        no file 'C:\luvit\lua\weblit\init.lua'
        no file '.\weblit.dll'
        no file 'C:\luvit\weblit.dll'
        no file 'C:\luvit\loadall.dll'
```

Running with luvit:
```
PS C:\luvit> .\luvit.exe myapp\main.lua
HTTP server listening at http://127.0.0.1:1337/
```

I'm I doing something wrong?
Thanks!

**Comment by creationix** [comment]
You have to also depend on `luvit/require` if you want the luvit style require system in luvi apps.

Also add `luvit/pretty-print` if you want to use the global `p` for debugging.

**Comment by creationix** [comment]
Sorry for the rough edge, making luvi apps is still a fairly advanced feature where I assume a little more experience.  Where should I place a note in the docs explaining that you probably want to depend on `luvit/require` and `luvit/pretty-print`?

**Comment by silverkorn** [comment]
No worry, to be honest I'm experimenting with `lit`, `luv`, `luvi` and `luvit`.

Theses terms were kind of confusing at first but it totally makes sense to include `luvit` core stuff in "myapp" since it's actually an application by itself built with `lit` under the `luvi` core and as it works properly for running the application as third party.

For the docs, it's quite complicated to judge the best place to add this information. 
For the current situation, `lit` was my first looking spot under `lit make` but as you said, following the flow of all the links between them would make more sense somewhere in the readme of `luvi`.

Otherwise, maybe this drawing I've made could be used somewhere on the page or in some documentation, where green highlights are the repositories and red highlights are the distributed binaries. This may help people visualize the whole sharding. (By the way, I still might be wrong with the whole concept, correct me if anything is not in place)

![luvit-flow](https://cloud.githubusercontent.com/assets/2325424/8093251/dd8f8cc8-0f8d-11e5-9e04-f99cc07378a3.png)

**Comment by creationix** [comment]
I love the diagram.  One thing that might confuse is you have the same "Lua" label for pure-lua things like lit and luvit as you have for Lua API bindings like luv, lua-zlib, and lua-openssl.

Also a fairly recent change is the zlib bindings aren't included by default and aren't in the official luvi builds, but there are miniz bindings (used for the zip asset bundle).  The miniz bindings are not in their own repo, but just included as part of the luvi source along with the bindings that expose read-write access to system environment variables.

**Comment by creationix** [comment]
Also there is a lua library baked into luvi that handles the fs/zip bundle API, some basic path join implementation and various utilities used to bootstrap things more easily.

**Comment by creationix** [comment]
Also I'm a little confused what the line between the red luvit and red lit signifies?  The only thing the luvit and lit binaries share is the luvi base and a few libraries from the luvit metapackage (require, http-codec, pretty-print, etc)

**Comment by creationix** [comment]
Sorry for nitpicking, but one more piece of feedback.

The source to luv is 100% C (implementing bindings using the Lua C API).  Everything else is just build system, unit tests or examples or documentation, but you have it labeled as "Lua".

But Luvi which you have labeled as "C/C++" is a mix of pure lua libraries and Lua C API bindings.

Also not that it's a big deal, but there is no C++ anywhere except for maybe compat. headers in some of the deep dependencies.  Luajit, libuv, zlib, openssl, luv, luvi, etc. are all vanilla C.  But I do understand that just the letter `C` has little context in a label.

So to recap, let me list the various parts:

## C Libraries

Implemented in C, used via C headers.

 - luajit
 - openssl
 - libuv
 - miniz
 - zlib

## Lua API Bindings

Implemented in C, consuming C libraries and exposing as Lua interfaces.

 - luv
 - miniz (inside luvi)
 - luvi's environment variable interface https://github.com/luvit/luvi/blob/master/src/lenv.c
 - luvi's windows service integration hooks https://github.com/luvit/luvi/blob/master/src/lminiz.c
 - lua-openssl
 - lua-zlib

## Lua Libraries

Logic implemented in pure Lua.

 - luvi's bootstrap code (luvi.path, luvi.bundle, etc) https://github.com/luvit/luvi/tree/master/src/lua
 - luvit (a metapackage containing many lua libraries)
 - lit (a metapackage containing many more lua libraries and reusing a couple from luvit)

Also luvit and lit can be used as libraries via `init.lua` in both repositories.

## Luvi Apps

Applications that combine lua code with luvi to form a standalone binary

 - lit
 - luvit

When packaged as a luvi app, the `main.lua` entry point is used instead of the library entry point.

**Comment by creationix** [comment]
The openssl bindings are in the `regular` flavor, but not the `tiny` flavor.  The zlib bindings aren't in either flavor and require a custom luvi build to use.

**Comment by silverkorn** [comment]
No problem, I'll see what I can make to make it more clear :smile: 

BTW, I've changed "myapp" __package.lua__ to this:
``` lua
return {
  name = "myapp",
  version = "0.0.1",
  dependencies = {
    "luvit/luvit@2.1.15",
    "creationix/weblit@0.3.1"
  }
}
```
Running the built application works but stops almost immediately and adding a `print('test')` at the end prints it... Is it possible the `.start()` doesn't loop properly?

**Comment by creationix** [comment]
You don't need all of luvit unless you want to use all of luvit's builtins.  Each package inside the luvit metapackage has it's interdependencies marked.

As far as the event loop not starting, you need to manually call `uv.run()` in a luvi app.

Since you are including all of luvit, you might be wanting a luvit style environment, See
https://github.com/luvit/luvit/blob/master/examples/custom-binary/main.lua for an example of how to make a luvit based luvi app.

**Comment by silverkorn** [comment]
Thanks, I'll try this! 

I will consider shared/repeated metapackages as part of their own Lua application to keep it lightweight and simple.

So here's another attempt for the diagram trying to follow what you meant :

![luvit-flow](https://cloud.githubusercontent.com/assets/2325424/8110684/aa56da16-102b-11e5-8441-7f070bb3c4c1.png)


Once again, let me know if there's still something wrong.
Thanks

**Comment by creationix** [comment]
The diagram looks great.  I wonder where I should put it.  Somewhere on luvit.io and/or in the various READMEs?

**Comment by silverkorn** [comment]
What about adding an entry called something like __Components__ or so in https://luvit.io/docs.html?

I could create additional images using the same diagram but with the current repository highlighted so you can add it in each READMEs with the correct repository.

I could also lend you the original SVG in case we need additional changes.

**Comment by creationix** [comment]
Original svg would be great.  Most browsers can render it nowadays and you could hyperlink the green parts.

**Comment by silverkorn** [comment]
I didn't know I could hyperlink in a SVG, that seems really nice, I'll give it a try.

**Comment by silverkorn** [comment]
I've made a pull request on https://github.com/luvit/luvit.io/pulls

The hyperlinks doesn't seem to work properly directly in Github with the _view_ option, you might want to test it before.

I've also added hyperlinks to the binary labels, __luvi__ to https://github.com/luvit/luvi/releases and __lit__ and __luvit__ to https://luvit.io/install.html.

**Comment by creationix** [comment]
It seems to work when I use `<embed>` to show the svg. https://luvit.io/docs.html

I tested in OSX Firefox and Chrome.

**Comment by silverkorn** [comment]
Great! It also works on Windows Firefox.

I guess this issue can now be closed.
Thank for the help!
