### ISSUE TITLE
Add an ability to hook the log

### ISSUE THREAD

**Issue by sousoux** [luvit/lit#90]
Lit currently picks up its log function from ./log which makes if difficult to redirect without a custom package. Would be good if you could pass a log function to core in the config table.

**Comment by creationix** [comment]
Good idea.  A hacky way is to replace `require('pretty-print').stdout`, then require log, then replace stdout with the original value.

```lua
do
  local pp = require('pretty-print')
  local stdout = pp.stdout
  local out = {}
  function out:write(...)
    -- Custom output
  end
  pp.stdout = out
  require('lit/libs/log')
  pp.stdout = stdout
end
```

It's hacky, I'll see about making an official API for it.

**Comment by creationix** [comment]
Ok, the interface to log changed a little.  To set a custom stream for the logger to write to do:

```lua
local out = {}
function out:write(...)
  -- custom output
end
require('lit/libs/log').stream = out
```

This can happen at any time before or after the first require to log happens.

**Comment by sousoux** [comment]
Many thanks
