### ISSUE TITLE
auto-update-checker broken (was: duplicate config file save while `lit update` + confusing output message)

### ISSUE THREAD

**Issue by lduboeuf** [luvit/lit#98]
Running `lit update` leads to duplicate config file save call . Output message "no connection to update server: lit.luvit.io" is always shown whatever situation.

``` shell
checking for update: 2.1.2
no connection to update server: lit.luvit.io
update config: ...
update config: ...
lit is up to date: 2.1.2
luvit is up to date: 2.2.2
updating luvi: v2.1.2
```

**Comment by creationix** [comment]
Thanks for the report.  It seems my auto-update checker is completely broken.  I've just removed it for now since it didn't work anyway.  We'll need to think of a better implementation for this.

**Comment by creationix** [comment]
Working on this in #102
